name: bios-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload bios.bin
      uses: actions/upload-artifact@v1
      with:
        name: bios.bin
        path: build/bios.bin
